### ISSUE TITLE
New Paste

### ISSUE THREAD

**Issue by wxyShine** [enchant97/hasty-paste#114]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is This A Security Issue?

- [X] This is not a security issue

### Describe The Problem

Internal Server Error
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

### Expected Behavior

```
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/.venv/lib/python3.10/site-packages/quart/app.py", line 1650, in handle_request
    return await self.full_dispatch_request(request_context)
  File "/app/.venv/lib/python3.10/site-packages/quart/app.py", line 1675, in full_dispatch_request
    result = await self.handle_user_exception(error)
  File "/app/.venv/lib/python3.10/site-packages/quart/app.py", line 1107, in handle_user_exception
    raise error
  File "/app/.venv/lib/python3.10/site-packages/quart/app.py", line 1673, in full_dispatch_request
    result = await self.dispatch_request(request_context)
  File "/app/.venv/lib/python3.10/site-packages/quart/app.py", line 1718, in dispatch_request
    return await self.ensure_async(handler)(**request_.view_args)
  File "/app/paste_bin/views/frontend.py", line 99, in post_new_paste
    paste_id = await paste_handler.create_paste(
  File "/app/paste_bin/core/paste_handler.py", line 57, in create_paste
    raise PasteHandlerStorageException() from err
paste_bin.core.helpers.PasteHandlerStorageException
```

**Comment by enchant97** [comment]
Can you add some more info into your issue. Such as what lead to the issue and what environment are you running (whether you are using the docker image or custom). If you are running from a custom environment please say what you are using: python version, system, etc.

**Comment by wxyShine** [comment]
3edf6bf567ec   ghcr.io/enchant97/hasty-paste:latest   "/bin/sh entrypoint.…"   2 days ago     Up 2 days (healthy)   0.0.0.0:9001->8000/tcp, :::9001->8000/tcp                                                        hasty-paste

**Comment by Bag72** [comment]
I got this issue when I removed the volume area in docker-compose.yaml and replaced it with a disk area.
    volumes:
      - ./data:/app/data
#volumes:
#  data:

Bring it up.  Select new, do some typing and as soon as you click Create that error comes up.    Not sure why it doesn't work but it doesn't.  I wanted to be able to purge the pastes down when I wanted without having an expiry data.

Could that be your issue.

**Comment by voodoopt** [comment]
i have same problem, my docker-compose,yaml

version: "3"
services:
  paste-bin:
    container_name: paste-bin
    image: ghcr.io/enchant97/hasty-paste:latest
    restart: unless-stopped
    volumes:
      - ./data:/app/data
    ports:
      - 8002:8000
    environment:
      - "TIME_ZONE=Europe/London"
#volumes:
#  data:"

with and witout # volumes # data 

"Internal Server Error
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application."

**Comment by StarryMoe** [comment]
Try adding this line in the docker-compose.yaml:
`user: UID:GID`
Change UID and GID to the user ID and group ID of the owner of the file directory you want to use, It works for me.
