### ISSUE TITLE
Potential Dockerfile Improvements

### ISSUE THREAD

**Issue by modem7** [enchant97/hasty-paste#19]
Heya, 

Great work so far! I'll be (re-)deploying this weekend!

I've been doing some work w/ Dockerfiles recently, and came across [COPY --link](https://docs.docker.com/engine/reference/builder/#copy---link) whilst working with `BUILDKIT_INLINE_CACHE=1` which may be useful.

Further information: 
* https://www.docker.com/blog/image-rebase-and-improved-remote-cache-support-in-new-buildkit

Docker workflow modifications for the above: 
* https://github.com/docker/setup-buildx-action#buildkit-daemon-configuration
* https://github.com/docker/build-push-action/blob/master/docs/advanced/cache.md

It's already damn clean though! Hope it helps reduce build times and sizes!

**Comment by enchant97** [comment]
Thanks for this. I'll have to do some testing, if everything goes well the next version will use this.

**Comment by enchant97** [comment]
Implemented in [V1.4.0](https://github.com/enchant97/hasty-paste/releases/tag/v1.4.0)
