### ISSUE TITLE
Feature request: Set default expiry time

### ISSUE THREAD

**Issue by modem7** [enchant97/hasty-paste#2]
Would it be possible to set a default expiry time for pastes via an env var in the coming versions? 

Thanks!

**Comment by enchant97** [comment]
> Would it be possible to set a default expiry time for pastes via an env var

Great idea! I've implemented it, you can switch to the "next" branch to try it out early.

Here's the environment variables:

| Name                         | Description                                   | Default       |
| :--------------------------- | :-------------------------------------------- | :------------ |
| DEFAULT_EXPIRE_TIME          | Enable a default expire time in web ui        | False         |
| DEFAULT_EXPIRE_TIME__MINUTES | Default minutes in ui for expiry if enabled   | 0             |
| DEFAULT_EXPIRE_TIME__HOURS   | Default hours in ui for expiry if enabled     | 1             |
| DEFAULT_EXPIRE_TIME__DAYS    | Default days in ui for expiry if enabled      | 0             |
