### ISSUE TITLE
Copy Share link doesn't work on Firefox 

### ISSUE THREAD

**Issue by meichthys** [enchant97/hasty-paste#26]
**Describe the bug**
The "Copy Share Link" button doesn't work on Firefox.
(It does work on Edge)

**To Reproduce**
1. In Firefox, open hastypaste website (behind reverse proxy - NginxProxyManager)
2. Click on "Copy Share Link"
3. Try to paste the link somewhere
4. See error in firefox console (see screenshot below)

**Expected behavior**
The link should copy as expected (it does on Edge)

**Screenshots**
![image](https://user-images.githubusercontent.com/10717998/185957441-fe537125-d96d-46cd-8c2a-2b20f5fdbd3a.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Firefox
 - Version v1.3

**Comment by enchant97** [comment]
@meichthys thanks for the bug report. It seems the "clipboard-write" permission is experimental and not currently supported in Firefox. I will add some backwards compatibility code so it will work.
