### ISSUE TITLE
"Copy Share Link" button does not work under http

### ISSUE THREAD

**Issue by EVOTk** [enchant97/hasty-paste#44]
**Describe the bug**
Copy Share Link bouton not run

**To Reproduce**
1. Create New Paste
2. Click on "Copy Share Link"
3. Paste or Ctrl+V
4. Not Share Link

**Expected behavior**
The "Copy Share Link" as work

**Screenshots**
https://user-images.githubusercontent.com/45015615/192137844-fd77f5df-9740-4833-8250-e3c5799cff8a.mp4

![2022-09-25 12-48-14](https://user-images.githubusercontent.com/45015615/192139712-eba84e31-2b04-4998-91bf-5836d0f853bf.png)

```
Uncaught (in promise) TypeError: navigator.clipboard is undefined
    copy_to_clipboard http://192.168.2.20:4010/static/script.js:6
    promise callback*copy_to_clipboard http://192.168.2.20:4010/static/script.js:6
    onclick http://192.168.2.20:4010/vBf05lnLf2NniEKpP7FTG7U7GbadXBM3oB8kqcRp:1
[script.js:6:19](http://192.168.2.20:4010/static/script.js)
    copy_to_clipboard http://192.168.2.20:4010/static/script.js:6
    (Asynchrone : promise callback)
    copy_to_clipboard http://192.168.2.20:4010/static/script.js:6
    onclick http://192.168.2.20:4010/vBf05lnLf2NniEKpP7FTG7U7GbadXBM3oB8kqcRp:1
```
https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Errors/Unexpected_type

**Install (please complete the following information):***
- Docker install
- Hasty Paste V1.5

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser : Chrome 105.0.5195.127 / Firefox 105 / Edge 105

Thx

**Comment by EVOTk** [comment]
Similar to https://github.com/enchant97/hasty-paste/issues/26

**Comment by EVOTk** [comment]
Hello,
Now that I've set up the reverse proxy, the button works normally. Maybe this is normal behavior?

**Comment by enchant97** [comment]
@EVOTk the clipboard API does not work under http connections unless localhost. In future I will remove the button if a non https connection is found, preventing unexpected results.

**Comment by EVOTk** [comment]
Thank you for your answer, I understand better :) I think we can close this :)
