### ISSUE TITLE
Add Optional in-memory caching

### ISSUE THREAD

**Issue by enchant97** [enchant97/hasty-paste#5]
- Use Memcached
- Must be optional
- Cache Items
    - Processed paste meta
    - Rendered content
- Provide docker-compose file pre-configured for easier deployment

**Comment by petersem** [comment]
Would this also have the option to use a redis cache?

**Comment by enchant97** [comment]
> Would this also have the option to use a redis cache?

Yes, I will be using a library that supports basic memory, memcached and redis.

**Comment by enchant97** [comment]
Implemented as of v1.6!
